### ISSUE TITLE
폴더 내 모두 스트리머 상태가 "오프라인 폴더" 필터링 기능

### ISSUE THREAD

**Issue by kdeun1** [rishubil/twitch-follower-organizer#20]
최상단에 폴더 버튼 우측에 "눈"모양으로 오프라인만 존재하는 폴더를 안보이게 하는 기능 추가 가능할까요?

**Comment by rishubil** [comment]
#8 과 동일 주제를 다루는 이슈이므로 본 이슈는 닫습니다.
