### ISSUE TITLE
아이콘이 엄청커져요

### ISSUE THREAD

**Issue by kspvillain** [rishubil/twitch-follower-organizer#23]
![image](https://user-images.githubusercontent.com/65124655/107705657-69f5a300-6d02-11eb-8143-effe97af47e9.png)
![image](https://user-images.githubusercontent.com/65124655/107705676-737f0b00-6d02-11eb-9b13-d31523d6c312.png)

거대해집니다

**Comment by rishubil** [comment]
440bcc1 에서 수정
