### ISSUE TITLE
익스텐션 적용된 부분만 Ctrl이나 Shift로 새 탭 새 창이 안뜹니다

### ISSUE THREAD

**Issue by kspvillain** [rishubil/twitch-follower-organizer#7]
익스텐션 적용된 부분만 Ctrl, Shift를 이용해서 새 탭, 새 창 띄우는게 안됩니다

영상이 커서 안올라가네요
https://youtu.be/gHj9iFxl9xE

다시한번 정말 감사드립니다

**Comment by rishubil** [comment]
말씀해주신 기능은 Ctrl, Shift 키를 사용하여 a 태그를 클릭하면 동작하는 기본 브라우저 기능인데,
현재 기본 a 태그의 클릭 이벤트를 강제로 변경하여 사용하다보니 기본 브라우저 기능이 동작하지 않는 것 같습니다.

클릭 이벤트를 처리하는 부분에서 처리를 해야할 것 같은데, 브라우저마다 새 탭, 새 창을 여는 단축키가 다를 수도 있을 것 같아 걱정입니다.
일단은 이벤트의 [getModifierState](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/getModifierState)를 확인하여 키보드 Modifier와 함께 클릭했을 경우 브라우저 기본 동작대로 작동하도록 수정하겠습니다.
